version: '3.8'

services:
  go-app:
    image: mydockerhubusername/myapp-go:latest
    container_name: go-app
    ports:
      - "8080:8080"
    networks:
      - myapp-network

  nextjs-app:
    image: mydockerhubusername/myapp-nextjs:latest
    container_name: nextjs-app
    ports:
      - "3000:3000"
    networks:
      - myapp-network

  wordpress:
    image: mydockerhubusername/myapp-wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - myapp-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

volumes:
  db_data:
