name: Go CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
    - name: Build Go Binary
      run: go build -o myapp .
    - name: Build and Push Docker Image
      run: |
        docker build -t myapp-go:latest .
        docker push myapp-go:latest
    - name: Deploy to Staging
      run: |
        echo "Deployment to staging completed successfully."
