name: WordPress CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
    - name: Install WordPress Dependencies
      run: composer install
    - name: Build and Push Docker Image
      run: |
        docker build -t myapp-wordpress:latest .
        docker push myapp-wordpress:latest
    - name: Deploy to Staging
      run:
        echo "Deployment to staging completed successfully."
